name: Cypress Tests Filtering - Tags, Chrome

on:
  workflow_dispatch: # Ruční spouštění

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: # Nastavení filtrování testů s tagem: @smoke
          env: grepTags=@smoke
          browser: chrome
